spring.application.name=notification

spring.config.import=configserver:http://localhost:8888

eureka.client.service-url.defaultZone= http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.profiles.active=dev

spring.web.resources.add-mappings=false  
spring.mvc.dispatch-options-request=true 


logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.server.HttpServer=DEBUG
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
logging.level.reactor.netty.http.client.HttpClient=DEBUG

spring.cloud.compatibility-verifier.enabled=false

